### ISSUE TITLE
API for "Generate lots of prompts"

### ISSUE THREAD

**Issue by anotherjesse** [fofr/prompter.fofr.ai#3]
It would be nice to have an API endpoint for generating lots of prompts

**Comment by fofr** [comment]
You can now make a GET request to the API call, count is limited to 1,000.

/api/generate:

https://prompter.fofr.ai/api/generate?promptTemplate=[geography.city]&count=100

**Comment by anotherjesse** [comment]
Nice!

Should the generate prompts have a `\r` at the end?

```
:["Karatau, Zhambyl, Kazakhstan\r","Karīmnagar, Telangana, India\r","Kutloanong, Orange Free State, South Africa\r","Severn, Maryland, United States\r","Sydney, New South Wales, Australia\r",
```

**Comment by fofr** [comment]
Looks like a side effect of just that list. Hmm.

**Comment by fofr** [comment]
`\r` is fixed now
https://github.com/ai-prompts/prompt-lists/commit/ef2cc66f4b1e1a035cae3a834004478824a8800f
